### ISSUE TITLE
Support pyproject.toml settings

### ISSUE THREAD

**Issue by nth10sd** [Gatewatcher/pytest-vulture#15]
It seems only settings in `vulture.ini` are supported. Please consider supporting vulture settings located in `pyproject.toml` of a project.

E.g.

```
[tool.vulture]
exclude = ["build/", "docs/source/conf_correct.py"]
make_whitelist = true
```

**Comment by MoranAbadieGatewatcher** [comment]
Thank you for your suggestion 🎉

I wanted to let you know that support for pyproject.toml configuration was added in version 2.2.0. You can now specify Vulture settings under the [tool.vulture] section in your pyproject.toml file, as shown here https://github.com/Gatewatcher/pytest-vulture?tab=readme-ov-file#configuring-with-pyprojecttoml

Could you please update to version 2.2.0 and give it a try? If you encounter any issues or have further feedback, feel free to share it here.

Thank you

**Comment by nth10sd** [comment]
Yes, it has been fixed, thank you!
